-- MySQL Script generated by MySQL Workbench
-- 08/13/14 15:51:08
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `houseNumber` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `careOf` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RegistrationDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RegistrationDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RegistrationDetails` (
  `idRegistrationDetails` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NULL,
  `date` MEDIUMTEXT NULL,
  PRIMARY KEY (`idRegistrationDetails`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ContactDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ContactDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ContactDetails` (
  `idContactDetails` INT NOT NULL AUTO_INCREMENT,
  `telephoneNumber` VARCHAR(45) NULL,
  `mobileNumber` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `skypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`idContactDetails`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `Address_idAddress` INT NOT NULL,
  `RegistrationDetails_idRegistrationDetails` INT NOT NULL,
  `ContactDetails_idContactDetails` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `status` SET('REGISTRATION_NOT_COMPLETE', 'ACTIVE', 'INACTIVE', 'BLOCKED') NULL,
  PRIMARY KEY (`idUser`, `Address_idAddress`, `RegistrationDetails_idRegistrationDetails`, `ContactDetails_idContactDetails`),
  INDEX `fk_User_Address_idx` (`Address_idAddress` ASC),
  INDEX `fk_User_RegistrationDetails1_idx` (`RegistrationDetails_idRegistrationDetails` ASC),
  INDEX `fk_User_ContactDetails1_idx` (`ContactDetails_idContactDetails` ASC),
  CONSTRAINT `fk_User_Address`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_RegistrationDetails1`
    FOREIGN KEY (`RegistrationDetails_idRegistrationDetails`)
    REFERENCES `mydb`.`RegistrationDetails` (`idRegistrationDetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ContactDetails1`
    FOREIGN KEY (`ContactDetails_idContactDetails`)
    REFERENCES `mydb`.`ContactDetails` (`idContactDetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Address`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Address` (`idAddress`, `street`, `houseNumber`, `postalCode`, `town`, `careOf`, `company`) VALUES (1, 'Peterstr.', '1', '31337', 'Peterstadt', '-', 'Peter Enterprises Inc.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`RegistrationDetails`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`RegistrationDetails` (`idRegistrationDetails`, `ip`, `date`) VALUES (1, '127.0.0.1', '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ContactDetails`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ContactDetails` (`idContactDetails`, `telephoneNumber`, `mobileNumber`, `fax`, `email`, `skypeName`) VALUES (1, '31337', '31337', '31337', 'peter@petersen.de', 'peter_p');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`User` (`idUser`, `Address_idAddress`, `RegistrationDetails_idRegistrationDetails`, `ContactDetails_idContactDetails`, `firstname`, `lastname`, `title`, `password`, `role`, `username`, `status`) VALUES (1, 1, 1, 1, 'Peter', 'Petersen', 'Dr.', 'peter', 'USER', 'peter', 'ACTIVE');

COMMIT;

